#!/usr/bin/env python3
"""
For each paragraph in a Spanish EPUB, insert an English translation
(generated by a local Ollama model) right after the original line.
Optionally change the book's title.

Usage:
    python translate_lines_epub.py input.epub output.epub \
        --model llama3.1 \
        --title "DoubleLanguage"

Requires:
    pip install ebooklib beautifulsoup4 requests --break-system-packages
    Ollama running locally (https://ollama.com) with a model pulled, e.g.:
        ollama pull llama3.1
"""

import sys
import argparse
import requests
from ebooklib import epub
import ebooklib
from bs4 import BeautifulSoup, NavigableString


def translate_text(text: str, model: str, ollama_url: str, source_lang: str) -> str:
    """Send text to a local Ollama model and return the English translation."""
    if not text.strip():
        return text

    prompt = (
        f"Translate the following {source_lang} text to English. "
        f"Respond with ONLY the translation, no notes, no quotes, no explanation.\n\n"
        f"{text}"
    )

    response = requests.post(
        f"{ollama_url}/api/generate",
        json={
            "model": model,
            "prompt": prompt,
            "stream": False,
        },
        timeout=120,
    )
    if response.status_code != 200:
        try:
            detail = response.json().get("error", response.text)
        except ValueError:
            detail = response.text
        raise RuntimeError(
            f"Ollama request failed ({response.status_code}): {detail}\n"
            f"Tip: run 'ollama list' to see available models, "
            f"and make sure '{model}' is pulled (ollama pull {model})."
        )
    return response.json()["response"].strip()


def add_translated_lines_to_html(html_content: str, model: str, ollama_url: str, source_lang: str) -> str:
    """Parse an HTML chapter and insert an English translation after each <p>."""
    soup = BeautifulSoup(html_content, "html.parser")

    paragraphs = soup.find_all("p")

    for p in paragraphs:
        original_text = p.get_text()
        if not original_text.strip():
            continue

        translated_text = translate_text(original_text, model, ollama_url, source_lang)

        translation_p = soup.new_tag("p")
        translation_p["class"] = "translation"
        translation_p.append(NavigableString(translated_text))

        p.insert_after(translation_p)

    return str(soup)


def process_epub(input_path: str, output_path: str, model: str, ollama_url: str, source_lang: str, title: str = None) -> None:
    book = epub.read_epub(input_path)

    doc_items = [item for item in book.get_items() if item.get_type() == ebooklib.ITEM_DOCUMENT]

    for i, item in enumerate(doc_items, 1):
        print(f"Translating chapter {i}/{len(doc_items)}: {item.get_name()}")
        original_content = item.get_content().decode("utf-8", errors="ignore")
        new_content = add_translated_lines_to_html(original_content, model, ollama_url, source_lang)
        item.set_content(new_content.encode("utf-8"))

    if title:
        book.metadata["http://purl.org/dc/elements/1.1/"]["title"] = []
        book.set_title(title)

    epub.write_epub(output_path, book)
    print(f"Done. Wrote: {output_path}")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Insert an English translation after each line/paragraph in an epub, using a local Ollama model.")
    parser.add_argument("input", help="Path to the input .epub file")
    parser.add_argument("output", help="Path to write the output .epub file")
    parser.add_argument("--model", default="llama3.1", help="Ollama model to use for translation (default: llama3.1)")
    parser.add_argument("--ollama-url", default="http://localhost:11434", help="Base URL of the Ollama server (default: http://localhost:11434)")
    parser.add_argument("--source-lang", default="Spanish", help="Source language of the book (default: Spanish)")
    parser.add_argument("--title", default=None, help="New title for the output epub (default: keep original title)")

    args = parser.parse_args()

    process_epub(args.input, args.output, args.model, args.ollama_url, args.source_lang, args.title)
