#!/usr/bin/env python3
"""
For each paragraph in an EPUB, insert an English translation
(generated by a local Ollama model) immediately after the original.

Optionally:
- Change the book title.
- Only process the first chapter (--debug).
- Render translations in italics.
- Render translations in a smaller font.

Usage:
    python translate_lines_epub.py input.epub output.epub

    python translate_lines_epub.py input.epub output.epub \
        --model llama3.1 \
        --title "DoubleLanguage" \
        --translation-italic \
        --translation-small

    python translate_lines_epub.py input.epub output.epub \
        --debug

Requires:
    pip install ebooklib beautifulsoup4 requests

    Ollama running locally:
        ollama pull llama3.1
"""

import argparse
import requests
import ebooklib
from ebooklib import epub
from bs4 import BeautifulSoup, NavigableString


def translate_text(text: str, model: str, ollama_url: str, source_lang: str) -> str:
    """Translate a string using a local Ollama model."""
    if not text.strip():
        return text

    prompt = (
        f"Translate the following {source_lang} text to English. "
        "Ignore broken text"
        "Respond with ONLY the translation."
        "Do not add notes, quotation marks, explanations, or commentary.\n\n"
        f"{text}"
    )

    response = requests.post(
        f"{ollama_url}/api/generate",
        json={
            "model": model,
            "prompt": prompt,
            "stream": False,
        },
        timeout=120,
    )

    if response.status_code != 200:
        try:
            detail = response.json().get("error", response.text)
        except ValueError:
            detail = response.text

        raise RuntimeError(
            f"Ollama request failed ({response.status_code}): {detail}\n"
            f"Run 'ollama list' to see installed models.\n"
            f"If necessary: ollama pull {model}"
        )

    return response.json()["response"].strip()


def add_translation_style(
    soup: BeautifulSoup,
    italic: bool,
    small: bool,
):
    """Inject CSS for translated paragraphs."""

    if not soup.head:
        return

    css = [".translation {"]

    if italic:
        css.append("font-style: italic;")

    if small:
        css.append("font-size: 0.9em;")

    css.append("}")

    style = soup.new_tag("style")
    style.string = "\n".join(css)
    soup.head.append(style)


def add_translated_lines_to_html(
    html_content: str,
    model: str,
    ollama_url: str,
    source_lang: str,
    italic: bool = False,
    small: bool = False,
) -> str:
    """Insert translated paragraphs after every original paragraph."""

    soup = BeautifulSoup(html_content, "html.parser")

    add_translation_style(soup, italic, small)

    paragraphs = soup.find_all("p")

    for p in paragraphs:
        original_text = p.get_text(strip=True)

        if not original_text:
            continue

        translated = translate_text(
            original_text,
            model,
            ollama_url,
            source_lang,
        )

        translation_p = soup.new_tag("p")
        translation_p["class"] = "translation"
        translation_p.append(NavigableString(translated))

        p.insert_after(translation_p)

    return str(soup)


def process_epub(
    input_path: str,
    output_path: str,
    model: str,
    ollama_url: str,
    source_lang: str,
    title: str | None = None,
    debug: bool = False,
    translation_italic: bool = False,
    translation_small: bool = False,
):
    book = epub.read_epub(input_path)

    doc_items = [
        item
        for item in book.get_items()
        if item.get_type() == ebooklib.ITEM_DOCUMENT
    ]

    if debug:
        print("DEBUG MODE: processing only the first chapters.")
        doc_items = doc_items[:4]

    total = len(doc_items)

    for i, item in enumerate(doc_items, start=1):
        print(f"Translating chapter {i}/{total}: {item.get_name()}")

        original = item.get_content().decode("utf-8", errors="ignore")

        translated = add_translated_lines_to_html(
            original,
            model,
            ollama_url,
            source_lang,
            italic=translation_italic,
            small=translation_small,
        )

        item.set_content(translated.encode("utf-8"))

    if title:
        book.metadata["http://purl.org/dc/elements/1.1/"]["title"] = []
        book.set_title(title)

    epub.write_epub(output_path, book)

    print(f"\nDone.\nOutput written to:\n{output_path}")


def main():
    parser = argparse.ArgumentParser(
        description="Insert an English translation after every paragraph in an EPUB using Ollama."
    )

    parser.add_argument(
        "input",
        help="Input EPUB file",
    )

    parser.add_argument(
        "output",
        help="Output EPUB file",
    )

    parser.add_argument(
        "--model",
        default="llama3.1",
        help="Ollama model (default: llama3.1)",
    )

    parser.add_argument(
        "--ollama-url",
        default="http://localhost:11434",
        help="Ollama server URL",
    )

    parser.add_argument(
        "--source-lang",
        default="Spanish",
        help="Source language (default: Spanish)",
    )

    parser.add_argument(
        "--title",
        help="New title for the output EPUB",
    )

    parser.add_argument(
        "--debug",
        action="store_true",
        help="Only translate the first chapter.",
    )

    parser.add_argument(
        "--translation-italic",
        action="store_true",
        help="Render translated paragraphs in italics.",
    )

    parser.add_argument(
        "--translation-small",
        action="store_true",
        help="Render translated paragraphs in a smaller font.",
    )

    args = parser.parse_args()

    process_epub(
        input_path=args.input,
        output_path=args.output,
        model=args.model,
        ollama_url=args.ollama_url,
        source_lang=args.source_lang,
        title=args.title,
        debug=args.debug,
        translation_italic=args.translation_italic,
        translation_small=args.translation_small,
    )


if __name__ == "__main__":
    main()
